# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Type Dom
xtagline:          
description:      
url:              http://typedom.com
baseurl:          /

author:
  name:           'Dominic A'
  url:            https://twitter.com/typedom

plugins:          [jekyll-paginate, jekyll-gist, pygments.rb]
paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          1.0

github:
  repo:           https://github.com/poole/hyde

# Social Media
twitter:          http://twitter.com/typedom
instagram:        http://instagram.com/typedom
flickr:           http://flickr.com/typedom
